# Configuring apache2
- name: apache2 configuration file
  copy: src=apache2.conf dest=/etc/httpd/apache2.conf
  notify: restart apache service

- name: create the webpage index.html
  copy: src=index.html dest=/var/www/html/index.html

